# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fraud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://creditcard1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c7767939f1f345db9f3fdc390a9decf9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4fb54c2fa80344e9ae567e54aa9c0d9d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: creditcard1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c7767939f1f345db9f3fdc390a9decf9 }}/cc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fraud'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ffcd9fc0f4340a29a112cd160d0061b }}
        images: 'creditcard1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c7767939f1f345db9f3fdc390a9decf9 }}/cc:${{ github.sha }}'